spring:
  application:
    name: ${APP_NAME:sentiment-ai-backend}

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:sentiment-ai-db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:false}

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      organization-id: ${OPENAI_ORGANIZATION_ID}
      project-id: ${OPENAI_PROJECT_ID}
      chat:
        model: gpt-4o